"use strict";
const name = '"Генератор защитного поля"';
let price;
price = 1000;
console.log(`Выбран ${name}, цена за штуку ${price} кредитов`);
price = 2000;
console.log(`Выбран ${name}, цена за штуку ${price} кредитов`);
console.log(1 + 2);
console.log("" + 1 + 2);
console.log(+"1" + parseInt("a2px"));
